''' ============================================================================
''' File: TemplateFileDefinition.vb
''' Project: RCH.TemplateStorage
''' Purpose: File definition model for template files within folders
''' Created: 2026-01-05
''' Author: TheForge
''' Status: Active
''' Version: 1.0.0
''' 
''' Description:
'''   New class (not extracted) for defining files within template folders.
'''   Supports file templates with placeholders for code generation and
'''   Forge metadata header requirements.
''' 
''' Features:
'''   - File name and type definition
'''   - Content template with placeholder support
'''   - Forge metadata header requirement flag
'''   - File encoding and line ending specifications
'''   - File-level metadata
''' 
''' Placeholder Support:
'''   Supports placeholders in ContentTemplate:
'''   - {ProjectName} - Project name
'''   - {CustomerCode} - Customer code
'''   - {Date} - Current date
'''   - {Author} - Author name
'''   - {Year} - Current year
'''   - Custom placeholders as needed
''' 
''' Dependencies:
'''   - None (standalone model)
''' 
''' Character Count: [Computed by ForgeAudit]
''' Last Updated: 2026-01-05
''' ============================================================================

Imports System

Namespace Models

    ''' <summary>
    ''' Represents a file definition within a template folder
    ''' </summary>
    Public Class TemplateFileDefinition

#Region "Database Properties"

        ''' <summary>
        ''' Unique identifier for database persistence (AutoIncrement Primary Key)
        ''' </summary>
        Public Property FileID As Integer

        ''' <summary>
        ''' Reference to the folder this file belongs to
        ''' </summary>
        Public Property FolderID As Integer

        ''' <summary>
        ''' Reference to the template (for direct access)
        ''' </summary>
        Public Property TemplateID As Integer

        ''' <summary>
        ''' File name with extension (e.g., "README.md", "Program.vb")
        ''' </summary>
        Public Property FileName As String

        ''' <summary>
        ''' File type/extension (e.g., ".md", ".vb", ".cs", ".txt")
        ''' </summary>
        Public Property FileType As String

        ''' <summary>
        ''' File description or purpose
        ''' </summary>
        Public Property Description As String

        ''' <summary>
        ''' Content template with placeholder support
        ''' Can contain placeholders like {ProjectName}, {Date}, {Author}, etc.
        ''' </summary>
        Public Property ContentTemplate As String

        ''' <summary>
        ''' Whether this file requires a Forge metadata header
        ''' </summary>
        Public Property RequiresMetadataHeader As Boolean = False

        ''' <summary>
        ''' Forge metadata header template (if RequiresMetadataHeader = True)
        ''' </summary>
        Public Property MetadataHeaderTemplate As String

        ''' <summary>
        ''' File encoding (e.g., "UTF-8", "ASCII", "UTF-16")
        ''' </summary>
        Public Property Encoding As String = "UTF-8"

        ''' <summary>
        ''' Line ending style (e.g., "CRLF", "LF")
        ''' </summary>
        Public Property LineEnding As String = "CRLF"

        ''' <summary>
        ''' Whether the file should be created automatically (vs. optional)
        ''' </summary>
        Public Property IsAutoGenerated As Boolean = True

        ''' <summary>
        ''' Display order within folder
        ''' </summary>
        Public Property DisplayOrder As Integer = 0

        ''' <summary>
        ''' Date and time the file definition was created
        ''' </summary>
        Public Property CreatedDate As DateTime = DateTime.Now

        ''' <summary>
        ''' Whether the file definition is active
        ''' </summary>
        Public Property IsActive As Boolean = True

#End Region

#Region "Constructors"

        ''' <summary>
        ''' Default constructor
        ''' </summary>
        Public Sub New()
        End Sub

        ''' <summary>
        ''' Constructor with file name
        ''' </summary>
        ''' <param name="fileName">File name with extension</param>
        Public Sub New(fileName As String)
            Me.FileName = fileName
            Me.FileType = System.IO.Path.GetExtension(fileName)
        End Sub

        ''' <summary>
        ''' Constructor with file name and content template
        ''' </summary>
        Public Sub New(fileName As String, contentTemplate As String)
            Me.FileName = fileName
            Me.FileType = System.IO.Path.GetExtension(fileName)
            Me.ContentTemplate = contentTemplate
        End Sub

        ''' <summary>
        ''' Full constructor with all core properties
        ''' </summary>
        Public Sub New(fileName As String, contentTemplate As String, description As String, requiresMetadataHeader As Boolean)
            Me.FileName = fileName
            Me.FileType = System.IO.Path.GetExtension(fileName)
            Me.ContentTemplate = contentTemplate
            Me.Description = description
            Me.RequiresMetadataHeader = requiresMetadataHeader
        End Sub

#End Region

#Region "Methods"

        ''' <summary>
        ''' Gets the file name without extension
        ''' </summary>
        Public Function GetFileNameWithoutExtension() As String
            If String.IsNullOrEmpty(FileName) Then Return String.Empty
            Return System.IO.Path.GetFileNameWithoutExtension(FileName)
        End Function

        ''' <summary>
        ''' Gets the file extension
        ''' </summary>
        Public Function GetExtension() As String
            If String.IsNullOrEmpty(FileName) Then Return String.Empty
            Return System.IO.Path.GetExtension(FileName)
        End Function

        ''' <summary>
        ''' Checks if the file is a code file (based on extension)
        ''' </summary>
        Public Function IsCodeFile() As Boolean
            Dim codeExtensions = {".vb", ".cs", ".js", ".ts", ".py", ".java", ".cpp", ".c", ".h", ".rb", ".php"}
            Return codeExtensions.Contains(FileType.ToLower())
        End Function

        ''' <summary>
        ''' Checks if the file is a documentation file
        ''' </summary>
        Public Function IsDocumentationFile() As Boolean
            Dim docExtensions = {".md", ".txt", ".doc", ".docx", ".pdf", ".html", ".xml"}
            Return docExtensions.Contains(FileType.ToLower())
        End Function

        ''' <summary>
        ''' Generates file content by replacing placeholders
        ''' </summary>
        ''' <param name="placeholders">Dictionary of placeholder values</param>
        Public Function GenerateContent(placeholders As Dictionary(Of String, String)) As String
            If String.IsNullOrEmpty(ContentTemplate) Then Return String.Empty

            Dim content = ContentTemplate

            For Each kvp In placeholders
                content = content.Replace($"{{{kvp.Key}}}", kvp.Value)
            Next

            Return content
        End Function

        ''' <summary>
        ''' Validates the file definition
        ''' </summary>
        ''' <returns>True if valid, False otherwise</returns>
        Public Function Validate(ByRef errorMessage As String) As Boolean
            If String.IsNullOrWhiteSpace(FileName) Then
                errorMessage = "File name is required"
                Return False
            End If

            If Not FileName.Contains("."c) Then
                errorMessage = "File name must include an extension"
                Return False
            End If

            If RequiresMetadataHeader AndAlso String.IsNullOrWhiteSpace(MetadataHeaderTemplate) Then
                errorMessage = "Metadata header template is required when RequiresMetadataHeader is True"
                Return False
            End If

            errorMessage = String.Empty
            Return True
        End Function

        ''' <summary>
        ''' Creates a clone of this file definition
        ''' </summary>
        Public Function Clone() As TemplateFileDefinition
            Return New TemplateFileDefinition() With {
                .FileName = Me.FileName,
                .FileType = Me.FileType,
                .Description = Me.Description,
                .ContentTemplate = Me.ContentTemplate,
                .RequiresMetadataHeader = Me.RequiresMetadataHeader,
                .MetadataHeaderTemplate = Me.MetadataHeaderTemplate,
                .Encoding = Me.Encoding,
                .LineEnding = Me.LineEnding,
                .IsAutoGenerated = Me.IsAutoGenerated,
                .DisplayOrder = Me.DisplayOrder,
                .IsActive = Me.IsActive
            }
        End Function

#End Region

    End Class

End Namespace
